version: '3'
services:
  test:
    env_file: .env
    environment:
      - FOO=${FOOVAR}
    image: alpine
    command: echo Value $FOO undefined
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager